### ISSUE TITLE
Javascript evaluation behavior

### ISSUE THREAD

**Issue by mistadikay** [axept/babel-plugin-transform-prejss#1]
Hey! Love this plugin, it helps me to migrate to JSS really quickly.

However, it looks like javascript evaluation is somewhat limited. For example, this will be evaluated:
```js
preJSS`
  content {
    background: ${(props) => `#fff url(${props.bg}) no-repeat`};
  }
`
```

But this will not:
```js
preJSS`
  content {
    background: #fff url(${(props) => props.bg}) no-repeat;
  }
`
```

Result will look like this:
```css
.content-0-126 {
    background: #fff url($^var__b4437b02-7ad4-1a12-c124-a6b8a508e7fc) no-repeat;
}
```

Is it expected behavior? If it is, maybe it makes sense to document it?

**Comment by sukazavr** [comment]
I have the same issue.
@mistadikay did you find a solution?

**Comment by mistadikay** [comment]
@sukazavr apparently it's just the way (react-)jss works — you can have functions only as a replacement of property values, but not inside of those values

**Comment by sukazavr** [comment]
@mistadikay but straight injections doesn't work too:
```JS
preJSS`
html {
  font-size: ${baseFontSizePx}px;
}
`
```
Trinspiled to:
```CSS
html {
  font-size: $^var__19e1c95c-a11c-54e0-d0eb-f10f33336d5dpx;
}
```
Is it a function too?
